### ISSUE TITLE
Library breaks with flutter 3.29.0

### ISSUE THREAD

**Issue by golanshy** [Mapk26/flutter_facebook_app_links#35]
After upgrading flutter from 3.27.4 to 3.29.0 my app fails to build with the error below.
Building the app using flutter 3.27.4 works as expected.

/Users/builder/.pub-cache/hosted/pub.dev/flutter_facebook_app_links-3.0.3/android/src/main/java/it/remedia/flutter_facebook_app_links/FlutterFacebookAppLinksPlugin.java:29: error: cannot find symbol
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
  symbol:   class Registrar
  location: interface PluginRegistry
1 error

FAILURE: Build failed with an exception.

**Comment by emiliodallatorre** [comment]
@golanshy you can find my fix in PR #36. Feel free to reference my branch in your pubspec until this is merged.

**Comment by golanshy** [comment]
Also needs a new build, flutter_facebook_app_links: ^3.0.3
Appreciate if you can complete it. :)
